modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/CodeOfArdonia/TooltipsReforged/issues"
license = "MIT"

[[mods]]
modId = "tooltips_reforged"
version = "${version}"
displayName = "Tooltips Reforged"
authors = "IAFEnvoy"
description = '''
Fully remake the whole tooltips and add various functions
'''
logoFile = "logo.png"

[[dependencies.tooltips_reforged]]
modId = "neoforge"
mandatory = true
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tooltips_reforged]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,1.21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tooltips_reforged]]
modId = "jupiter"
mandatory = true
versionRange = "[2.3.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "tooltips_reforged.mixins.json"